Blog.create(title: "My First Mission", date: "1/24/2016
", body: "As I sit in my NYC apartment on my last day in the city I ponder what will be the next steps in my life. I was watching the Social Network the other day and seeing Jessie Eisenberg blog about every thing that he was doing and numerous recommendations from my peers, I will take up blogging again. While completing the Dev Bootcamp program’s educational part was great the career week didn’t exactly go as I thought it would. It actually went better, because as I previously thought that they would place you in companies, they moreover give you tips on how to get a job. At first I though that this wasn’t what I was looking for, but it brings me more into what I need to do to become employed in the tech field.\n

With my current qualifications and experience I am placed on the bottom end of the spectrum for full stack developers in the industry. The key to this is experience as I have discovered. There are a lot of senior developer jobs out there, but there aren’t that many junior developer jobs out there. The ones that I’ve seen are very under whelming. There are all these people who tell you that junior developer jobs probably aren’t going to pay you more than 60K in your first year, depending on where your living.\n

Now, what do I need to do to get where I want to be. I just recently took up this thing of making yearly goals. My yearly goal this year is to be at a top tech. company by February of 2017. Now how am I going to do this? Experience. I roughly have a little over the year to achieve as much experience to classify me as a senior developer. While years of experience range for different types of jobs the type of experience I want to have is about 2-3. With this experience I get put in a whole other bracket.\n

So how am I going to cram this much experience into a year? Good question, but I ran the numbers and this is what it look like. The average person who works a 40 hour work week a year approximately works 2,080 hours a year. That doubled is 4,160 hours in a year. There are only 8760 hours in a year, so… this is going to be a lot of work.\n
When I move home to Michigan tomorrow I will experiment with 80 hour work weeks and maybe even look to extend the number in the future. I am a huge gym rat so I must be able to go to the gym while working this much. Say hello to bringing meal prepping back baby! This means that I will prepare all my meals for the week on Sunday, so I won’t have to worry about getting the proper nutrition during the week.\n
I’ve realized while I have a personal site on Github, it was made before I started the immersive program at Dev Bootcamp and I’ve gained a ton of skills since then. My first call to order which I will either start today or tomorrow is to revamp my website because I need a place to store my blogs. I will build this website using the Rails framework and look into implementing Angular.js with it. I’ve also been relearning Python lately. I can’t wait to start building projects again in that language.\n
I will begin to start blogging more about the process and I will commit to it. I’m confident in myself that I will be able to achieve my end goal by next year, all it takes is hard work. I will leave you with one of the best thing I’ve heard Elon Musk say in an interview, If you work 100 hour work weeks then in four months you will have achieved what someone else who works 40 hours weeks achieves in a year. ")

  Blog.create(title:"Challenges in Python and Personal Website", date: "1/26/2016", body:"Well it turns out that learning Python and building a new personal website for yourself can get difficult at times. Today I wanted to achieve two things. They were to build a roman numerals converter in Python and do some work on the frame work of my website, so i’ll have a place to actually put these blogs. I started the Python project around 5:30pm and unfortunately I effectively ended up going down a rabbit hole.\n
What my problem was Is that I didn’t time box my self well. If I had set up a time to say “ok lets switch over to the website”, I feel I would have got around to at least working on both projects.\n
For tomorrow, however, I will definitely make an effort to time box myself better so I don’t end up going down another rabbit hole. On the bright side I did learn a lot about Python tonight.\n
As I sit here at 2am in the morning I think about what I could of done differently with the Python project. I realized that once I was stuck to the fact that I wanted to use a dictionary to solve this, there was no going back. This unfortunately may have eliminated some easier ways to solve the roman numeral converter, but I haven’t used dictionaries all to much in a while so I thought I would get some practice. \n
Since relearning classes a couple days ago they are now coming second nature to me. The hardest part about this Python project, moreover, was how a dictionary in Python is structured. While my foolish self wanted to think it could be similar to a hash in Ruby, I was in for a rude awakening. Not only does a Python dictionary not have any built in sort methods, the only way you can structure a dictionary in a semi sorted way is by the order that items are inserted in. The method of doing this was called OrderedDict. This method essential changed the dictionary into a duck type (I hope that’s what you call it in Python) object. This gave me all sorts of problems while constructing a modern roman numeral converter for numbers.\n
Positive things that came out of tonight were that I learned about Python’s module collections. There are a lot of useful methods in this module and I can’t wait to experiment with more of them. Another thing I learned about Python is from the looks of it I can easily start turning my projects into a MVC format. This is great, but I do still need to do more work on the MVC model in JavaScript! \n
Besides not having the time to give my website the ability to let me store these blogs on them, I feel I still learned a lot today. I really want to get back into coding in JavaScript and will probably work on some code academy challenges for it. After I get my website to a decent point I have multiple things I can do. My father wants me to build him a website, so I think that that would be a good challenge for me to do. Also, I want to learn more about Angular. I’ve only used it twice before and it looks like it makes things a lot easier manipulating JSON objects. Hopefully, I get to a decent point for my personal website by this weekend!" )

Blog.create(title: "Mobile Responsive Websites", date: "1/28/2016", body: "
Today I wanted to just work on my website. Yesterday, I felt really good about designing my website, and I was making making great progress. I wanted to style the whole site in just css and no design frameworks. I was doing great and the design was looking very elegant and sleek. However, what I realized when I was working on my website today was that it isn’t mobile responsive.\n
Mobile responsive, how hard could that be to implement on your site? Well from what I found it can be challenging to grasp the topic. I took to Google looking for answers and I found three good ways to do it. One is to use media queries to tell the browser what to adjust the styling to when the window is at different lengths. This looks challenging to understand this concept, but from what I’ve gathered is that you set at what pixel length min or max that you want some content to change. Next is that you would need to target every item in another css selector and make all of those adjusted to fit the screen at that pixel length. You would then give that new css selector a attribute of that specified pixel length so that that class is added to the content. This will inherently make it mobile responsive when the window is the size range of that selector’s pixel length.\n
The other two options that I’ve seen are using frameworks from the web. Most notable of them was bootstrap because I’ve had experience using it before. However, since I want to stick to my original goal of not using a web frame work I wont be using it. I have to admit that I’ve kind of cheated on this goal and did add bootstrap to mess around with it, but after coming back and realizing my goal I will not be using bootstrap.\n
So media queries it is! I’m excited to learn more about this topic an hopefully I’m able to pick it up quickly. I will start tomorrow leaning more about how to add this to my site. Tomorrow, I plan to code more in Python and JavaScript. I will moreover, be focused on my website, but I feel a good front end backend mixed day will be the perfect fit for a Friday.
" )

Blog.create(title: "Website Working Copy By Sunday", date: "2/2/2016", body: "As I may have said before about my focus of being home and wanting to move out, I have been very lethargic lately. A friend of mine who I haven’t seen in a while visited me all the way from Florida. It was great to see him, but do to his presence I wasn’t able to get as much accomplished as I would of liked.\n
This week, however, I’m ready to rock and roll. I’ve already set a goal to have a working copy of my website deployed to a server by Sunday. Features I really want to put on it are things like mobile responsiveness and a place to store my blogs. I’ve been doing a lot of research on mobile responsiveness and I’m almost ready to get after it.\n
While doing my research on mobile responsiveness I realized that I would need some kind of photo editing software. I decided to purchase Adobe Photoshop and boy was I in for a lot. There are so many things that you can do with photoshop I feel that I’ve barley gazed the surface. A couple features I hope to implement on my website include back-groundless photos and resizing different photos for the different scene sizes my website will accompany.\n
This goal is pretty ambitious given my lack of experience in website design, but all my friends are either at work or out of the state. This means that I can work undistracted for this whole week. This week I’m really going to see how close I can get to working to about 80 or over 80 hours a week coding. I couldn’t be more excited for this challenge and I can’t wait to see it live.")


Blog.create(title:"Personal Website Status", date: "2/7/2016", body:"I’ve done it(well sort of); I have completed my website. While my personal website will never actually be 100% complete I did, however,  accomplish my goal of having a ready to deploy personal website. While I was going to deploy this website today, I kind of had something come up that has taken some of my focus away from this. Recently I got lucky enough to schedule an interview for a financial company that is hiring full stack engineers. While I met most of the qualifications on the list, there was one that I didn’t have any prior knowledge of which was Java.\n

While I’m expecting to hear when exactly this upcoming week I will be interviewed, I will try my best to learn as much of Java as possible. Last Friday, when I received this news I hopped in my car and went right to the bookstore to pick up a beginners guide to Java. I also have already started doing some code academy lessons about the language. At first glance it feels more like machine code than I’m accustomed to, but I couldn’t be more intrigued to learn the language.\n

Unfortunately, trying to learn a brand new programming language while trying to meet a hard deadline for your website can be quite a daunting task. Even though I wasn’t able to deploy my website to the web I’m very happy with the progress I made. I’m also proud of the progress that I’ve made learning Java. I hope to build a project in the language within the upcoming week.\n

While I am a little nervous for this interview, I also feel that I couldn't be more ready. Since August I’ve took the plunge into being a full time developer and couldn’t be more happy with the decision. All the all nighters, missed family events, and lack of responsiveness to friends I’ve endured during this 6 month span, I hope to use that to my advantage during this hiring process. I’m now addicted to this life style of coding all day and night. I honestly love it, it’s weird to say that but I believe I found my passion in life.")

Blog.create(title: "Constantly Driving Forward", date: "2/11/2016", body:"Well as my job hunt has been pretty slow I’m also happy to announce that I’ve finally put my website online. This was actually the easiest part. I got a custom domain name for GoDaddy for $20 for two years. I also am hosting the website on Heroku. I chose to use Heroku because of its seamless integration with Rails and Postgres. It looks good to be able to search for your website but, there are a few issues with the site.\n

One thing that I’ve noticed is that even though my Website is responsive to large, medium, and small screens. There are problems with formatting for mobile screens. Currently, when someone is looking at my website on an iPhone 6 it looks great. However, on almost any other phone there are issues with content being cut off.  From what I found out is that I’m going to have to write multiple media queries to account for these screen sizes on different phones. I will look into solving this formatting issue tomorrow.\n

Next problem I discovered is that Heroku, even though it is free, put .herokuapp in the url. This could potentially be a big killer for future search engine optimization. Yesterday, I tried to fix this problem by using a ruby gem called rack-canonical-host. From what the documentation said to do was install the gem and set an environmental variable that would store your canonical host url, but it wasn’t that simple. \n

While trying to do this I accidentally cut off connection between Chrome and my local host. The problem was that whenever I tried to go to a localhost in development mode it would automatically redirect to my custom domain name. As I may have forgot to mention clear enough before is that my GoDaddy custom domain is redirecting to the Heroku server and it is displaying the .herokuapp. This problem took a while to diagnose and treat. What I eventually did to solve the problem was to do a clear cache and hard reload through the browser. This established the connection between Chrome and my local host.\n

Even though I solved that problem I still am unable to get rid of the .herokuapp in the url. I will look into this tomorrow as well as the screen formatting. Another thing I’ve noticed from my website is that the color scheme isn’t great. The color scheme looks very bland and boring. I will do some research on what are the best colors to use on a website later.\n

Also, as I mentioned in my last blog, I stated learning Java last Friday and it’s turning out to be a little tricker to grasp than I accepted. While I’m 250+ pages into my Head First Java book I still find it a bit difficult to fully code programs in the language. Nevertheless, I’m learning a lot not just about Java, but OO design in general, as mostly everything in Java needs to be an object.\n

Finally, lets talk about Python. I feel that I have a great grasp on Python. I do have one problem with the language and it’s how the object oriented part of it works. While Python is an Object Oriented Language it has different implementations. I’m having trouble figuring out how to instantiate a class within another class, and pass variables between them. In Ruby this is pretty straight forward to do, but in Python it does get a little tricky to implement. I’m going to hopefully pick up a more advanced Python book this week. Hopefully, I will find the answers to this and many other things in there.\n
One last thing! Once I write this responsiveness for my website I am going to take up another big project. I believe I’m going to use rails and a couple api’s to devices a simple but fun game. I can’t wait to get started on that!")

Blog.create(title: "Problem Solved!", date: "2/15/2016", body: "Finally! I’ve solved a problem that has taken me almost a week to figure out. The problem being that whenever I went to my custom domain it would redirect to ryanlesson.herokuapp.com and show that in the browser. I wanted it to only show ryanlesson.com in the browser. After doing extensive research on the topic and reaching out to a few friends I was finally able to get it.\n

What I had to do was hide my Heroku app in the ww subdomain of my custom domain. To do this I found that creating a CNAME file through my DNS provider would be the answer. I then created a CNAME file and linked it to my Heroku app server. To my surprise this only worked when I typed www.ryanlesson.com and not just ryanlesson.com.\n

To fix this I had to permanently forward ryanlesson.com to www.ryanlesson.com. I was having some trouble doing this because Heroku has some issues with using A host types connecting to naked domains. What I eventually did was delete my A host file and set the forwarding appropriately. While this seems like an easy task to do understanding what was going on was extremely difficult, especially for a first timer.\n

I had to rummage through multiple article on how to complete this process and the documentation on the Heroku webpage isn’t the greatest on how to do this. One problem I was finding on these help forums was that they were extremely dated, at least 5 years old. Thanks to my friend Bruno who I reached out to that helped me understand what was going on and how to complete this process, I was able to finally hook everything up accordingly.\n

Tomorrow will be my first interview with a tech company called TMC bonds. I am applying for a full stack developer position within the company. I can’t wait for this interview! I really hope to be challenged by them if they send me a coding challenge. I really want to bring to fruition any weakness I may have.\n

Also, I’ve been leaning a lot of Java from the book I’m reading called Head First Java. While I’m pretty far into the book, they don’t really give you good instructions on how to code your own challenge. They moreover give you concepts and syntax information. I hope to complete the book by the end of this week.\n

Finally, since my personal website is at where I want it to be I will lay off updating it and put my focus into a new project. This doesn’t mean I will stop updating my website all together it just means that I will be spending less time on it. My idea is to build a simple yet fun game. I want to make this project very heavily JavaScript oriented so I’m going to use Angular.js to build this application. I will also be using API to help achieve my end goal. I will keep you updated on its status in the upcoming weeks.")

Blog.create(title:"Time to Get Real", date:"2/16/2016", body:"Today was finally the day. I had my first technical interview ever. I was so excited and I’ve been preparing for this for 2 weeks. Well it turns out that I completely bombed it. For some reason I just didn’t know the answers to the questions. Some of the topics I’ve heard before and others just left me bewildered and anxious just to reply with something. All in all it was a great experience. I learned a lot from the at interview. Even though they said they are going to talk it over internally about the final decision, I am pretty sure they will not offer me a job.\n

So………. where to go from here. Well after applying online to what seems like 40+ companies, I’ve received numerous emails from those companies about not pursing me as a potential candidate. Even though rejection does suck, I just coupe with it and move on to the next opprotunity. While getting all these rejection emails something occurred to me. The only interview I got was from a networking connection I received through Dev Bootcamp.\n

Now it became very clear to me what I need to do to get a job as a developer and that is to network and build connections in the industry. One problem in where I live in Michigan is that there aren’t any networking or connections I can really make. Detroit may seem like a viable candidate, but I’ve never really been drawn to that city like other people have. I interned down their when I was in college and when you left work it usually was a race to get out of the city.\n

What I’m looking at now is Chicago. While I did love it in NYC I’m just too broke to move back out their again. As well as in NYC there is a DBC in Chicago. I already reached out to one of the career advisors about visiting the campus to get some work done and she was very willing to let me do that. She seems like a very nice lady and I hope to meet her in person soon.\n

Now that I know I have to move to Chicago, I need to figure out how exactly I’m going to do that. Right now I have just enough money to put me in the city for about a month or two. Should I really just move out to Chicago with no guarantee of a job? Absolutely! Right now I feel that I’m trapped in my little desk in my room. I’m not in the same environment as DBC and I feel that may be the reason that I’m not working as effectively as I used to. If I stay at home I feel that I will eventually need to start to find work in other fields because of my limited networking opportunities.\n

I’ve been searching a lot on Air Bnb's and there seems to be some good apartments right next to the DBC campus I could rent out. I’ve really never been to Chicago before. Well that’s a lie, I was their once when I was 4, but I don’t remember it. This move may seem sort of drastic to some people, but if I want to get a job in a field I want this seems like a no brainer. Also, I still have a lot other companies I’ve applied that are based in Chicago. Moving their would give me a vantage point to easily schedule and go to interviews. I will keep you updated on how this goes.")