Blog.create(title: "My First Mission", date: "1/24/2016
", body: "As I sit in my NYC apartment on my last day in the city I ponder what will be the next steps in my life. I was watching the Social Network the other day and seeing Jessie Eisenberg blog about every thing that he was doing and numerous recommendations from my peers, I will take up blogging again. While completing the Dev Bootcamp program’s educational part was great the career week didn’t exactly go as I thought it would. It actually went better, because as I previously thought that they would place you in companies, they moreover give you tips on how to get a job. At first I though that this wasn’t what I was looking for, but it brings me more into what I need to do to become employed in the tech field.\n

With my current qualifications and experience I am placed on the bottom end of the spectrum for full stack developers in the industry. The key to this is experience as I have discovered. There are a lot of senior developer jobs out there, but there aren’t that many junior developer jobs out there. The ones that I’ve seen are very under whelming. There are all these people who tell you that junior developer jobs probably aren’t going to pay you more than 60K in your first year, depending on where your living.\n

Now, what do I need to do to get where I want to be. I just recently took up this thing of making yearly goals. My yearly goal this year is to be at a top tech. company by February of 2017. Now how am I going to do this? Experience. I roughly have a little over the year to achieve as much experience to classify me as a senior developer. While years of experience range for different types of jobs the type of experience I want to have is about 2-3. With this experience I get put in a whole other bracket.\n

So how am I going to cram this much experience into a year? Good question, but I ran the numbers and this is what it look like. The average person who works a 40 hour work week a year approximately works 2,080 hours a year. That doubled is 4,160 hours in a year. There are only 8760 hours, so… this is going to be a lot of work.\n
When I move home to Michigan tomorrow I will experiment with 80 hour work weeks and maybe even look to extend the number in the future. I am a huge gym rat so I must be able to go to the gym while working this much. Say hello to bringing meal prepping back baby! This means that I will prepare all my meals for the week on Sunday, so I won’t have to worry about getting the proper nutrition during the week.\n
I’ve realized while I have a personal site on Github, it was made before I started the immersive program at Dev Bootcamp and I’ve gained a ton of skills since then. My first call to order which I will either start today or tomorrow is to revamp my website because I need a place to store my blogs. I will build this website using the Rails framework and look into implementing Angular.js with it. I’ve also been relearning Python lately. I can’t wait to start building projects again in that language.\n
I will begin to start blogging more about the process and I will commit to it. I’m confident in myself that I will be able to achieve my end goal by next year, all it takes is hard work. I will leave you with one of the best thing I’ve heard Elon Musk say in an interview, If you work 100 hour work weeks then in four months you will have achieved what someone else who works 40 hours weeks achieves in a year. ")

  Blog.create(title:"Challenges in Python and Personal Website", date: "1/26/2016", body:"Well it turns out that learning Python and building a new personal website for yourself can get difficult at times. Today I wanted to achieve two things. They were to build a roman numerals converter in Python and do some work on the frame work of my website, so i’ll have a place to actually put these blogs. I started the Python project around 5:30pm and unfortunately I effectively ended up going down a rabbit hole.\n
What my problem was Is that I didn’t time box my self well. If I had set up a time to say “ok lets switch over to the website”, I feel I would have got around to at least working on both projects.\n
For tomorrow, however, I will definitely make an effort to time box myself better so I don’t end up going down another rabbit hole. On the bright side I did learn a lot about Python tonight.\n
As I sit here at 2am in the morning I think about what I could of done differently with the Python project. I realized that once I was stuck to the fact that I wanted to use a dictionary to solve this, there was no going back. This unfortunately may have eliminated some easier ways to solve the roman numeral converter, but I haven’t used dictionaries all to much in a while so I thought I would get some practice. \n
Since relearning classes a couple days ago they are now coming second nature to me. The hardest part about this Python project, moreover, was how a dictionary in Python is structured. While my foolish self wanted to think it could be similar to a hash in Ruby, I was in for a rude awakening. Not only does a Python dictionary not have any built in sort methods, the only way you can structure a dictionary in a semi sorted way is by the order that items are inserted in. The method of doing this was called OrderedDict. This method essential changed the dictionary into a duck type (I hope that’s what you call it in Python) object. This gave me all sorts of problems while constructing a modern roman numeral converter for numbers.\n
Positive things that came out of tonight were that I learned about Python’s module collections. There are a lot of useful methods in this module and I can’t wait to experiment with more of them. Another thing I learned about Python is from the looks of it I can easily start turning my projects into a MVC format. This is great, but I do still need to do more work on the MVC model in JavaScript! \n
Besides not having the time to give my website the ability to let me store these blogs on them, I feel I still learned a lot today. I really want to get back into coding in JavaScript and will probably work on some code academy challenges for it. After I get my website to a decent point I have multiple things I can do. My father wants me to build him a website, so I think that that would be a good challenge for me to do. Also, I want to learn more about Angular. I’ve only used it twice before and it looks like it makes things a lot easier manipulating JSON objects. Hopefully, I get to a decent point for my personal website by this weekend!" )

Blog.create(title: "Mobile Responsive Websites", date: "1/28/2016", body: "
Today I wanted to just work on my website. Yesterday, I felt really good about designing my website, and I was making making great progress. I wanted to style the whole site in just css and no design frameworks. I was doing great and the design was looking very elegant and sleek. However, what I realized when I was working on my website today was that it isn’t mobile responsive.\n
Mobile responsive, how hard could that be to implement on your site? Well from what I found it can be challenging to grasp the topic. I took to Google looking for answers and I found three good ways to do it. One is to use media queries to tell the browser what to adjust the styling to when the window is at different lengths. This looks challenging to understand this concept, but from what I’ve gathered is that you set at what pixel length min or max that you want some content to change. Next is that you would need to target every item in another css selector and make all of those adjusted to fit the screen at that pixel length. You would then give that new css selector a attribute of that specified pixel length so that that class is added to the content. This will inherently make it mobile responsive when the window is the size range of that selector’s pixel length.\n
The other two options that I’ve seen are using frameworks from the web. Most notable of them was bootstrap because I’ve had experience using it before. However, since I want to stick to my original goal of not using a web frame work I wont be using it. I have to admit that I’ve kind of cheated on this goal and did add bootstrap to mess around with it, but after coming back and realizing my goal I will not be using bootstrap.\n
So media queries it is! I’m excited to learn more about this topic an hopefully I’m able to pick it up quickly. I will start tomorrow leaning more about how to add this to my site. Tomorrow, I plan to code more in Python and JavaScript. I will moreover, be focused on my website, but I feel a good front end backend mixed day will be the perfect fit for a Friday.
" )

Blog.create(title: "Website Working Copy By Sunday", date: "2/2/2016", body: "As I may have said before about my focus of being home and wanting to move out, I have been very lethargic lately. A friend of mine who I haven’t seen in a while visited me all the way from Florida. It was great to see him, but do to his presence I wasn’t able to get as much accomplished as I would of liked.\n
This week, however, I’m ready to rock and roll. I’ve already set a goal to have a working copy of my website deployed to a server by Sunday. Features I really want to put on it are things like mobile responsiveness and a place to store my blogs. I’ve been doing a lot of research on mobile responsiveness and I’m almost ready to get after it.\n
While doing my research on mobile responsiveness I realized that I would need some kind of photo editing software. I decided to purchase Adobe Photoshop and boy was I in for a lot. There are so many things that you can do with photoshop I feel that I’ve barley gazed the surface. A couple features I hope to implement on my website include back-groundless photos and resizing different photos for the different scene sizes my website will accompany.\n
This goal is pretty ambitious given my lack of experience in website design, but all my friends are either at work or out of the state. This means that I can work undistracted for this whole week. This week I’m really going to see how close I can get to working to about 80 or over 80 hours a week coding. I couldn’t be more excited for this challenge and I can’t wait to see it live.")


Blog.create(title:"Personal Website Status", date: "2/7/2016", body:"I’ve done it(well sort of); I have completed my website. While my personal website will never actually be 100% complete I did, however,  accomplish my goal of having a ready to deploy personal website. While I was going to deploy this website today, I kind of had something come up that has taken some of my focus away from this. Recently I got lucky enough to schedule an interview for a financial company that is hiring full stack engineers. While I met most of the qualifications on the list, there was one that I didn’t have any prior knowledge of which was Java.\n

While I’m expecting to hear when exactly this upcoming week I will be interviewed, I will try my best to learn as much of Java as possible. Last Friday, when I received this news I hopped in my car and went right to the bookstore to pick up a beginners guide to Java. I also have already started doing some code academy lessons about the language. At first glance it feels more like machine code than I’m accustomed to, but I couldn’t be more intrigued to learn the language.\n

Unfortunately, trying to learn a brand new programming language while trying to meet a hard deadline for your website can be quite a daunting task. Even though I wasn’t able to deploy my website to the web I’m very happy with the progress I made. I’m also proud of the progress that I’ve made learning Java. I hope to build a project in the language within the upcoming week.\n

While I am a little nervous for this interview, I also feel that I couldn't be more ready. Since August I’ve took the plunge into being a full time developer and couldn’t be more happy with the decision. All the all nighters, missed family events, and lack of responsiveness to friends I’ve endured during this 6 month span, I hope to use that to my advantage during this hiring process. I’m now addicted to this life style of coding all day and night. I honestly love it, it’s weird to say that but I believe I found my passion in life.")